import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Loader from "@/components/UI/Loader/Index";
import { NextUIProvider } from "@nextui-org/system";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Orelsa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Loader>
          <NextUIProvider>{children}</NextUIProvider>
        </Loader>
      </body>
    </html>
  );
}
